spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    data:
      host:  ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}


logging:
  level:
    org.hibernate.SQL: debug


cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
      image-path: "images/"
      presigned-url-expires-minutes: 10
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}


imp:
  api:
    key: ${IMP_API_KEY}
    secret: ${IMP_API_SECRET}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-expiration-time: 360000000
  issuer: ${JWT_ISSUER}

web3j:
  private-network: ${WEB3J_PRIVATE_NETWORK}
  chain-id: ${WEB3J_CHAIN_ID}
  token-contract-address: ${WEB3J_TOKEN_CONTRACT_ADDRESS}
  funding-contract-address: ${WEB3J_FUNDING_CONTRACT_ADDRESS}
  keyfile-password: ${WEB3J_KEYFILE_PASSWORD}
